### ISSUE TITLE
How to correct for leap-seconds?

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#14]
OBS dataloggers do not (to my knowledge) account for leap seconds, so the data (and possibly the clock sync) needs to be corrected for this.

In the recommended clock correction section, we specify that the "reference" (GNSS, in general) and instrument times should be compared for the beginning and end of the experiment, and maybe at intermediate times if the drift is measureably non-linear. 

My question is: should the instrument time provided be "adjusted" for any leap-seconds?

FOR:
- Drift correction calculations do not need to account for leap seconds: if users DON'T do this, then the proposed msmod drift correction will skew everything
- If intermediate clock comparisons are provided, it is much easier to figure them out if the leap-second has already been eliminated from the equation.

AGAINST:
- the term "instrument time" implies the time indicated by the instrument, not a corrected time
- Correcting the leapsecond offset programmatically avoids operator error.

I'm not sure how this would work for time cross-correlations or John's CSAC-correction: would these be more logical in one case than in the other?

Ideally, the instrument times would be the true ones and the leap second correction (which would be run before correcting clock drift) would somehow modify the instrument times in the clock comparison file, maybe adding a "time zone" like +00:01 to the given time to indicate that the leap second was corrected?

**Comment by jac5796** [comment]
Yes, the times should be adjusted for leap seconds.

			J
************************************************************
John A. Collins
Dept. of Geology and Geophysics, MS 24
Woods Hole Oceanographic Institution
360 Woods Hole Road
Woods Hole, MA 02543

e-mail: 	***@***.***
voice:	+1-508-289-2733
**********************************************

**Comment by WayneCrawford** [comment]
- Wrote recommendation in [standards.md](docs/standards.md)  to have this, as well as recommendations on which sense the intrument syncs should be shifted.  
- Bring up case where this might not be advisable (many sync_times and/or multiple leap seconds, would need to be careful to avoid operator error, or specifically not adjust the inst_sync_times.  
- Added a "corrected_in_syncs_instrument` boolean field to the `leapsecond` field: true by default but can be set to false.
