### ISSUE TITLE
2024 AGU Abstract

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#16]
A first draft:

The FDSN Action Group on Marine Seismology Data and Metadata Standards

(alphabetical list of Action Group Members, + WG chairs?)

Marine seismological data are crucial to studying many local, regional and global-scale processes, including subduction zones, mid-ocean spreading centers, interplate volcanos, deep and shallow hot-spots, mantle circulation and global earth structure.  It is crucial that these data arrive at FDSN-standard data centers and that they are useable by the entire seismological community.  The FDSN Action Group on Marine Seismology Data and Metadata Standards is working to develop and publish an international standard for marine-specific data and metadata standards, as well as a list of validated open-source tools for processing specific to marine data.  We aim to propose these standards to the FDSN at the summer 2025 Lisbon IASPEI meeting.  We present here the current state of the proposed standards and invite you to comment on and/or add to them.

**Comment by WayneCrawford** [comment]
Second draft:

The Federation of Digital Seismology Networks Action Group on Marine Seismology Data and Metadata Standards

Wayne Crawford, Kasey Aderhold, Yinshuang Ai, Jerry Carter, John Collins, Carlos Corela, Susanne Hemmleb, Takehi Isse, Joel Simon, Maria Tsekhmistrenko

Marine seismology data are crucial to studying many local, regional and global-scale processes, including subduction, ocean crust accretion, interplate volcanism, deep and shallow hot-spots, mantle circulation and global earth structure. Marine seismology data are often subtly but significantly different than land data: the dataloggers often suffer clock drift (there is no GPS signal at the ocean floor), the instruments are often not oriented with respect to geographic north, and there are unique noise and signal sources (ocean waves, seafloor currents, ships, whales...).  It is crucial that these data are distributed by Federation of Digital Seismology Networks (FDSN)-standard data centers and that they are useable by the entire seismological community. The FDSN Action Group on Marine Seismology Data and Metadata Standards is developping an international standard for marine seismology data and metadata, in addition to a list of validated open-source tools for marine-specific processing tools. The Action Group aims to propose these standards at the summer 2025 Lisbon IASPEI meeting. We present here the current state of the proposed standards and invite you to use them, comment on them and/or suggest additions to them.

**Comment by WayneCrawford** [comment]
Here's the abstract with your recommended change in bold.  I might also add "subduction zone seismicity" but I think it's already included in "subduction" (one could argue that "mid-ocean ridge seismicity" is included in "ocean crust accretion", but I don't have a great alternative inspiration):

The Federation of Digital Seismology Networks Action Group on Marine Seismology Data and Metadata Standards

Wayne Crawford, Kasey Aderhold, Yinshuang Ai, Jerry Carter, John Collins, Carlos Corela, Susanne Hemmleb, Takehi Isse, Joel Simon, Maria Tsekhmistrenko

Marine seismology data are crucial to studying many local, regional and global-scale processes, including subduction, ocean crust accretion, interplate volcanism, deep and shallow hot-spots, mantle circulation and global earth structure, as well as **mid-ocean ridge and transform fault seismicity**. Marine seismology data are often subtly but significantly different than land data: the dataloggers suffer clock drift (there is no GPS signal at the ocean floor), the sensors are usually not oriented with respect to geographic north, and there are unique noise and signal sources (ocean waves, seafloor currents, ships, whales...). These data should be distributed by Federation of Digital Seismology Networks (FDSN)-standard data centers and they should be packaged/explained so that all seismologists can easily use them. The FDSN Action Group on Marine Seismology Data and Metadata Standards is developping an international standard for marine seismology data and metadata, in addition to a list of validated open-source tools for marine-specific processing tools. The Action Group aims to propose these standards at the summer 2025 Lisbon IASPEI meeting. We present here the current state of the proposed standards and invite you to use them, comment on them and/or suggest additions to them.

**Comment by KaseyAderhold** [comment]
Just a small typo to correct, third to last line: "The FDSN Action Group on Marine Seismology Data and Metadata Standards is **developping** (developing) an international standard for marine seismology data and metadata, in addition to a list of validated open-source tools for marine-specific processing tools. "

**Comment by WayneCrawford** [comment]
Abstract submitted
