### ISSUE TITLE
If/how to specify time base nominal drift (or precision)

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#20]
Currently, the field `drift:time_base` is open text, and the example in [standards.md](doc/standards.md) contains both the Model and the "nominal drift", which Wayne probably copied from the documentation.  Questions include:
- Should we include "nominal drift" information?
- If so
    - would it be better named "precision" (or "nominal precision")?
    - should it be left in the `time_base` field (no standard for whether to put it there or not, but also no strict requirement for verification) or in a separate field (`nominal_precision`?, `nominal_drift`)?

@KAderhold was afraid that, without some verification by the user, the value communicated by the manufacturer could be false
@JCollins considers that using the manufacturer's value is not a problem and gives a reference for whether the actual observed drift can be considered "within spec" or not

**Comment by jac5796** [comment]
Yes, if we name the clock, then it is useful to quote the expected drift rate.  I would be happy with leaving the specification “in the time_base field”.  No requirement to add a value.
I suggest using the term “Drift Rate”, and specify as either 2 x 10^-8 or 20 PPB (parts per billion).


			J
************************************************************
John A. Collins
Dept. of Geology and Geophysics, MS 24
Woods Hole Oceanographic Institution
360 Woods Hole Road
Woods Hole, MA 02543

e-mail: 	***@***.***
voice:	+1-508-289-2733
**********************************************

**Comment by WayneCrawford** [comment]
Add optional field "nominal_drift_rate"
