### ISSUE TITLE
What parameters for cubic spline interpolation?

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#26]
Need to answer this in able to present a new proposal to companies (#24)

For the cubic spline, have to choose which type:
- "natural": 2nd deriv = 0 at the control points
- other boundary conditions on the curves

Other possibile interpolations are (from scipy 1.14.0)
- "akima1d": how does this work?
- "pchipinterpolator": how does this work?

Should write a simple code to compare the results of each

Note that our case is a simplification of the general case, since control points are monotonically increasing.

We want to avoid putting too much curvature on big stretches of time, allow more in small stretches:
- metric minimizing curvature*length?
- metric minimizing deviation from linear interpolation?

**Comment by WayneCrawford** [comment]
Roberto Cabieces Diaz sent me an example of their measurements and polynomial fits from the UPFLOW experiment.  I have not yet had time to evaluate the possibility of using a cubic spline in place of their polynomial fit, but I would expect that it would be possible as long as we have as many time points as they have polynomial coefficients:

> Hello Wayne, I attach you a relative disperse fitting from UP33. I
> attach you also the polynom and the data inside the pickle file
> "UP_33_rel". This type of file is what I made for the UPFLOW. It is nice
> because can be readed using python and basically is a dictionary with
> polynom info (numpy 1d polunom object) and the vectors with the data and
> dates, plus stattime and endtime and skew.
> 
> I do not think that the type of regresion fit change significantly the
> results, might be at the edges of the curve. For me works with polynoms
> up to order 3.

<img width="952" alt="UP33" src="https://github.com/user-attachments/assets/112ef1af-5a28-46ee-83ea-f27be17d5fab">

<img width="869" alt="UP33_rel" src="https://github.com/user-attachments/assets/9958e23e-8587-4386-841c-030994b6ddea">

**Comment by jac5796** [comment]
Wayne

> With the two test datasets I used (exaggerated changes in drift rate), only pchip and akima1 always had a positive first derivative. 

Is it really the case that “pchip” and akima1” enforce a positive first derivative?  I read the documentation as saying the interpolating curve between nodes is either monotonically increasing, decreasing or constant.

One would not want an interpolating curve that enforces a positive or negative first derivative because the offset of some clocks with near-zero drift can switch sign.  


			John

************************************************************
John A. Collins
Dept. of Geology and Geophysics, MS 24
Woods Hole Oceanographic Institution
360 Woods Hole Road
Woods Hole, MA 02543

e-mail: 	***@***.***
voice:	+1-508-289-2733
**********************************************

**Comment by WayneCrawford** [comment]
You are right, and I didn't see that it could be monotonically decreasing!  And, as you noted, the spline is being applied to the offset between the reference and the instrument, which could change sign as the clock speeds up or slows down.  My simple tests indicate that a positive or negative first derivative doesn't affect the desired monotonically increasing nature of both clocks, as the drift is several orders of magnitude smaller than the clock rate (O(1e-8) for calibrated Seascans, O(1e-6) for the worst cases I've seen).  I've added a check that the offset between each records does not change by more than half a sample after the clock correction, which itself very strictly enforces a monotonic increase in instrument time: a 4096-byte record with perfect Steim2 compression (~7000 samples), would still require a locally O(1e-4) drift to fail, which I think would be a valid failure.

**Comment by WayneCrawford** [comment]
Closing based on meeting and changes made to msmod clock correction specification file.
