### ISSUE TITLE
Specify dip is SEED standard?

### ISSUE THREAD

**Issue by joelsimon** [FDSN/OBS-standards#3]
As opposed to SAC standard (90 degrees offset).

**Comment by WayneCrawford** [comment]
Added footnote:
[^1]: StationXML/Seed Dip is degrees down from horizontal.  SAC analog is +90 degrees ([`CMPINC` : Component incident angle (degrees from upward vertical)](https://ds.iris.edu/files/sac-manual/manual/file_format.html)

**Comment by WayneCrawford** [comment]
Strange, the footnote got removed from my comment, here it is again:

[^1]: StationXML/Seed Dip is degrees down from horizontal.  SAC analog is +90 degrees ([`CMPINC` : Component incident angle (degrees from upward vertical)](https://ds.iris.edu/files/sac-manual/manual/file_format.html)
