### ISSUE TITLE
Add leap-second correction line to msmod?

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#33]
Currently, instructions for correcting leap seconds include two slightly complicated calls to msmod.

For example, for a positive leap second on 2016-12-31T23:59:60, the calls are :
```
msmod --timeshift -1 -ts 2016,366,23:59:59.999999'
msmod –-actflags ‘4,1’ –tsc 2016,366,23:59:59.999999 –tec 2016,366,23:59:59.999999
```

It would be simpler to have a specific msmod command, such as
```
msmod -lsp 3692217600	37
```
where the above values are directly copied from the leap-seconds.list file, or
```
msmod -lsp 2017,1,0,0,0
```
which is clearer, but requires the operator to calculate the day of/after the leap second (easier for 1 january than for 1 july!)

Any thoughts on this?

I'm not sure if this is something that should be combined in the request to the software company, or if Chad Trabant could more easily (and readily) code it himself.

Cheers

**Comment by jac5796** [comment]
Wayne
	Would be great to have option of one command only.  

	Why not have the option to either seconds or datetime string?

			John
	
************************************************************
John A. Collins
Dept. of Geology and Geophysics, MS 24
Woods Hole Oceanographic Institution
360 Woods Hole Road
Woods Hole, MA 02543

e-mail: 	***@***.***
voice:	+1-508-289-2733
**********************************************

**Comment by WayneCrawford** [comment]
[Document(https://github.com/FDSN/OBS-standards/blob/main/other/leap_second_msmod_addition.md) approved by group, includes both date and seconds specifications.
