### ISSUE TITLE
Should we include miniSEED 3 information?

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#35]
In a recent Epos-France technical meeting, miniSEED3 discussion was pushed to the future because of the huge amount of changes needed in the processing flow.  Should we load down the documents with miniSEED3 information while it is still in a state of flux?

Start a third document with "future directions"?

**Comment by CarterJerryEarthScope** [comment]
I think we should!  miniSEED3 is the future for seismic data, even if
uptake is slow at the moment.
Jerry A Carter, Ph.D.
Data Services Coordinator
***@***.***

<https://www.earthscope.org>

**Comment by joelsimon** [comment]
I second that

**Comment by WayneCrawford** [comment]
keep miniseed3 in the main document
