### ISSUE TITLE
Drift correction document

### ISSUE THREAD

**Issue by WayneCrawford** [FDSN/OBS-standards#37]
This issue is for discussion of the [drift correction document ](https://github.com/FDSN/OBS-standards/blob/main/other/msmod_drift_addition.md)and [associated test files](https://github.com/FDSN/OBS-standards/tree/main/other/drift_correct).

Wayne modified the document and sent it out by email on 9 October 2024. An email discussion started, which is probably better followed and recorded by this issue system.  The next few "responses" are copies of the emails already sent.

**Comment by WayneCrawford** [comment]
On 10 October 2024 at 10:05:57, Wayne Crawford ([crawford@ipgp.fr](mailto:crawford@ipgp.fr)) wrote:

> Thanks John and Joel for your feedback.  Another thought: the log file is pretty for humans to read but less simple for a computer to parse.  What do you think of changing 
> 
```
> Rec#  | Original time              | Corrected time             | Difference | Offset from start
> ----- | -------------------------- | -------------------------- | ---------- | -----------------
>     0 | 2022-01-01T00:00:00        | 2022-01-01T00:00:00        |      0.000 |               0
>     1 | 2022-01-10T04:02:00        | 2022-01-10T04:02:00.005000 |      0.005 |          792120
>     2 | 2022-01-19T08:04:00        | 2022-01-19T08:04:00.009800 |      0.010 |         1584240
>     3 | 2022-01-28T12:06:00        | 2022-01-28T12:06:00.014100 |      0.014 |         2376360

```
> 
> to
> 
 ```
  # RecNo  Original time              Corrected time              Corrected-Original   Original-sync_inst[0]
       0   2022-01-01T00:00:00.00000  2022-01-01T00:00:00                    0.00000                 0.00000
       1   2022-01-10T04:02:00.00000  2022-01-10T04:02:00.00500              0.00500            792120.00000
       2   2022-01-19T08:04:00.00000  2022-01-19T08:04:00.00980              0.00980           1584240.00000
       3   2022-01-28T12:06:00.00000  2022-01-28T12:06:00.01410              0.01400           2376360.00000
 ```
> 
> which is still human readable, but simpler to parse (for example with str.split() in Python).  I also made explicit what("Offset from start" is, and normalized the printout of all seconds to 5 decimal points (the miniSEED standard).
> 
> Please give me your opinions on all of these modifications.

**Comment by WayneCrawford** [comment]
I've got another thought, perhaps the log file columns should be ordered with the corrected time before the original time, for better coherence with the clock_corrections file, in which the reference time is in the first column and the instrument time in the second.  An example:

## clock_correction_linear1.txt
```
type: piecewise_linear
# Reference time         Instrument time
2022-01-01T00:00:00Z     2022-01-01T00:00:00Z
2023-01-01T00:00:00Z     2023-01-01T00:00:01.5Z

```` 

## Current log file
```
# RecNo  Original time              Corrected time             Corrected-Original  Original-sync_inst[0]
      0  2022-01-01T00:00:00.00000  2022-01-01T00:00:00.00000             0.00000                0.00000
      1  2022-01-10T04:02:00.00000  2022-01-10T04:01:59.96230            -0.03770           792120.00000
      2  2022-01-19T08:04:00.00000  2022-01-19T08:03:59.92460            -0.07540          1584240.00000

```

## Proposed log file 
```
# RecNo  Corrected time             Original time              Corrected-Original  Original-sync_inst[0]
      0  2022-01-01T00:00:00.00000  2022-01-01T00:00:00.00000             0.00000                0.00000
      1  2022-01-10T04:01:59.96230  2022-01-10T04:02:00.00000            -0.03770           792120.00000
      2  2022-01-19T08:03:59.92460  2022-01-19T08:04:00.00000            -0.07540          1584240.00000

```

**Comment by mary-tsekhmistrenko** [comment]
Hi Wayne, 
to change the log file to "still human readable" looks good to me and makes it less prone to parsing issues. I don't quite see the advantage of swapping "original time" and "corrected time". I thought that was OK as is, but as long as we have the column names on the top we can also swap it, if you think it is more coherent.

**Comment by WayneCrawford** [comment]
Hi Maria,

I think it's important that the input and output files have the same column order, so that it's easy for the user to validate what was done.  The input file has the following order:
`{reference_time} {instrument_time}` 
whereas the current log file has  the order
`{original_time} {corrected_time}`
Since the {original_time} is the {instrument_time} in the first file and the {corrected_time} should match the {reference_time}, the columns in the two files are swapped with respect to each other.

I thought the easiest solution would be to swap the order in the log file, but another option is to swap the order in the input file:

## Option 1: flip the log file columns

input file header: `#      Reference time     Instrument time`
log file header: `# RecNo  Corrected time     Original time     Time correction(corr-orig)  Original-input_inst[0]`

## Option 2: flip the input file columns

input file header: `#      Instrument time    Reference time`
log file header: `# RecNo  Original time      Corrected time     Time correction(corr-orig)  Original-input_inst[0]`

Any preferences?  If you have better column headers for the log file, feel free to suggest them, too!

## Notes

- I changed the log files third column name to "Time correction (corr-orig)" to be clear that this is the value that will be placed in field 16 of the data record header
- Renaming the top row is not an option because it is a comment line that is not read by the parser, and in any case I think
it's better to have a standard than to leave open several interpretations.

**Comment by WayneCrawford** [comment]
Arguments for option 1:
- Time correction is in the presented order (corr-orig)
- Reference time first "makes sense" in input file
    - Reference time would probably be the x-axis in any reference vs instrument time plots

Arguments for option 2:
- Original time first "makes sense" in log file
- Specifying instrument and reference times is a bit cleaner in YAML/JSON format if there was no sync:
   Currently: `~; 2024-08-24T06:00:00`
   Would be: `2024-08-24T06:00:00; ~`

**Comment by WayneCrawford** [comment]
Changed to option 2, but with clearer correspondance of column names:

- input file header:
   ```
    # Instrument time    Reference time
    ```
- log file header:
   ```
    # RecNo  Instrument time      Corrected to reference     Corrected-Instrument  Instrument-sync_inst[0]
   ```
